version: "3.8"

services:
  fiat-db:
    image: postgres
    ports:
      - 5432:5432
    container_name: fiat-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: JunkPass4321
      POSTGRES_DB: fiat
    volumes:
      - fiat-db-volume:/var/lib/postgresql/data
    networks:
      - fiat-network

  fiat-backend:
    build: ./Backend
    container_name: fiat-backend
    ports:
      - 3000:3000
    depends_on:
      - fiat-db
    networks:
      - fiat-network
    volumes:
      - "./Backend:/Backend"

    environment:
      SERVERHOST: "localhost"
      SERVERPORT: 3000
      PGUSER: "postgres"
      PGPASSWORD: "JunkPass4321"
      PGHOST: "fiat-db"
      PGDATABASE: "fiat"
      PGPORT: 5432
      DBDIALECT: "postgres"
      SESSIONSECRET: "sessionsecret123"
      COOKIESECRET: "cookiesecret123"
      NODE_ENV: "development"

networks:
  fiat-network:
    driver: bridge

volumes:
  fiat-db-volume:
