version: "3.8"

services:
  fiat-db:
    image: mariadb:lts-jammy
    ports:
      - 3306:3306 # MariaDB uses port 3306 by default
    container_name: fiat-db
    environment:
      MYSQL_ROOT_PASSWORD: JunkPass4321
      MYSQL_DATABASE: fiat
      MYSQL_USER: fiatuser
      MYSQL_PASSWORD: JunkPass4321
    volumes:
      - fiat-db-volume:/var/lib/mysql # MariaDB data directory
    networks:
      - fiat-network

  fiat-backend:
    build: ./server
    container_name: fiat-backend
    ports:
      - 3000:3000
    depends_on:
      - fiat-db
    networks:
      - fiat-network
    volumes:
      - "./server:/server"
    environment:
      SERVERHOST: "localhost"
      SERVERPORT: 3000
      MYSQL_USER: "fiatuser"
      MYSQL_PASSWORD: "JunkPass4321"
      MYSQL_HOST: "fiat-db"
      MYSQL_DATABASE: "fiat"
      MYSQL_PORT: 3306
      DBDIALECT: "mariadb" # Updated to use MariaDB dialect if your ORM supports it
      SESSIONSECRET: "sessionsecret123"
      COOKIESECRET: "cookiesecret123"
      NODE_ENV: "development"

networks:
  fiat-network:
    driver: bridge

volumes:
  fiat-db-volume:
